spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fullstackjava
    username: rachid
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true